### ISSUE TITLE
gmum.py start

### ISSUE THREAD

**Issue by ktalik** [gmum/gmum.r#486]
Things to research:

1. http://www.swig.org/ (general tool for connection with various environments)
2. http://www.boost.org/doc/libs/1_58_0/libs/python/doc/index.html (Python <- C++)
3. http://sourceforge.net/projects/armanpy/ (Python <- C++ with Arma)

**Comment by ktalik** [comment]
gmum.py start is ready. Here is some info for @kjurek and @marcinMarcin:

You can now `make` `cec` and `svm` draft wrappers:

```
$ make
mkdir -p swig/cec swig/gng swig/svm
touch gmumpy/__init__.py
swig -c++ -outdir gmumpy -python -o swig/cec_wrap.cxx interface/cec.i
swig -c++ -outdir gmumpy -python -o swig/svm_wrap.cxx interface/svm.i
g++ -O2 -fPIC -larmadillo -c swig/cec_wrap.cxx -o swig/cec_wrap.o -I /usr/include/python2.7 -I include -I include/svm -I include/cec
g++ -O2 -fPIC -larmadillo -c swig/svm_wrap.cxx -o swig/svm_wrap.o -I /usr/include/python2.7 -I include -I include/svm -I include/cec
g++ -shared  src/svm/svm_basic.o swig/svm_wrap.o -o gmumpy/_svm.so
g++ -shared  src/cec/cec_configuration.o  src/cec/hartigan.o swig/cec_wrap.o -o gmumpy/_cec.so
```

At this point, there is ability to import svm wrapper and create `SVMConfiguration` like this:

```python
$ python2
Python 2.7.8 (default, Sep 24 2014, 18:26:21) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gmumpy import svm
>>> sc = svm.SVMConfiguration()
>>> sc
<gmumpy.svm.SVMConfiguration; proxy of <Swig Object of type 'SVMConfiguration *' at 0x7f7eb8e38d80> >
```

However cec import is not working.

```python
>>> from gmumpy import cec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gmumpy/cec.py", line 28, in <module>
    _cec = swig_import_helper()
  File "gmumpy/cec.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cec', fp, pathname, description)
ImportError: gmumpy/_cec.so: undefined symbol: _ZNK4gmum7Cluster7entropyEv
```
TODO list:
1. Fix cec import
2. Package structure, main module (or init)
3. Prepare more generic Makefile / merge with gmum library Makefile (including splitting) / switch to CMake
4. The rest
